# SITE CONFIGURATION
title: ACM@MANOA # your site title
author: ACManoa # You :P
description: > # Meta description of Homepage
  ACManoa is the largest computer science student organization at the University of Hawaii at Manoa. We welcome students of all different backgrounds, interests, and skill levels to join our community and share in our passion for CS. ACM is split into different special interest groups (SIG's) â€” each with a different goal. Although some events may "belong" to a certain group, being a member of a special interest group is the same as being a member of ACManoa. Our events are always and will always be open to everyone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acmanoa.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: ACManoa
  links:
#   - https://twitter.com/BenBalter
#   - https://www.facebook.com/ben.balter
#   - https://www.linkedin.com/in/BenBalter
#   - https://plus.google.com/+BenBalter
    - https://github.com/acmanoa
#   - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  The Association for Computing Machinery at the University of Hawaii at Manoa

hero_img: posts/post.JPG # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: acmmanoa@hawaii.edu # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  acmanoa # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
discord: https://discord.gg/pnrYV5T
mailchimp: http://eepurl.com/bOCcTP

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
